create table SALARIES(
ID NUMBER(*,0) PRIMARY KEY,
EMPLOYEE_ID NUMBER(*,0) NOT NULL,
PROJECT_ID NUMBER(*,0),
SALARY NUMBER(10,2) NOT NULL CHECK (SALARY>500),
CONSTRAINT CHECK_SALARY CHECK (SALARY > 500)
);

CREATE TABLE  PROJECTS(
ID NUMBER(*,0) PRIMARY KEY,
CODE VARCHAR2 (255 BYTE) NOT NULL,
MANAGER_ID NUMBER(*,0),
BUDGET NUMBER(10,0) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE
);

CREATE TABLE  EMPLOYEES(
ID NUMBER(*,0) PRIMARY KEY,
MANAGER_ID NUMBER(*,0),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2(255 BYTE) NOT NULL
);

alter table "SYSTEM"."SALARIES" add constraint FK_SALARY_EMPLOYEE foreign key("EMPLOYEE_ID") references "EMPLOYEES"("ID");
alter table "SYSTEM"."SALARIES" add constraint FK_SALARY_PROJECT foreign key("PROJECT_ID") references "PROJECTS"("ID");
alter table "SYSTEM"."PROJECTS" add constraint FK_MANAGER_PROJECT foreign key("MANAGER_ID") references "EMPLOYEES"("ID");
alter table "SYSTEM"."EMPLOYEES" add constraint FK_MANAGER foreign key("MANAGER_ID") references "EMPLOYEES"("ID");

DROP TABLE SALARIES;
DROP TABLE PROJECTS;
DROP TABLE EMPLOYEES;

SELECT 
  COUNT(E.ID) AS COUNT 
FROM 
  EMPLOYEES E
INNER JOIN
  PROJECTS P
ON
  E.ID = P.MANAGER_ID
WHERE
  P.CODE = '44905736599';
  
SELECT 
  E.FULL_NAME
FROM 
  EMPLOYEES E
INNER JOIN
  SALARIES S
ON
  E.ID = S.EMPLOYEE_ID
WHERE
  S.SALARY BETWEEN 1000 AND 2500;
  
SELECT 
  P.CODE
  ,COUNT(E.ID) AS COUNTER
FROM 
  EMPLOYEES E
INNER JOIN
  PROJECTS P
ON
  E.ID = P.MANAGER_ID
GROUP BY
  P.CODE
ORDER BY CODE ASC;

SELECT 
  E.*
  ,P.CODE
FROM 
  EMPLOYEES E
LEFT JOIN
  PROJECTS P
ON
  E.ID = P.MANAGER_ID
WHERE 
  P.CODE IS NULL;
  
SELECT 
  M.FULL_NAME || ' - ' || E.FULL_NAME  AS employee_boss
FROM 
  EMPLOYEES E
LEFT JOIN
  EMPLOYEES M
ON
  E.ID = M.MANAGER_ID;
  
SELECT 
  E.*
FROM 
  EMPLOYEES E
WHERE 
  E.FULL_NAME LIKE '%Kermit%';

